version: 3.0.{build}-{branch}
os: Visual Studio 2017
configuration: Release
skip_tags: true
environment:
  FRAMEWORK: netcoreapp2.1
  matrix:
    - RUNTIME: noruntime
    - RUNTIME: win-x86      	
    - RUNTIME: linux-x64
    - RUNTIME: osx-x64
assembly_info:
  patch: true
  file: '**\SolutionInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  account_feed: false
  project_feed: false
install:
- ps: Install-Product node ''
- cmd: |
    dotnet restore
    cd Rnwood.Smtp4dev
    npm install
    cd ..
build_script:
 - cmd: dotnet build Smtp4dev.sln -c %Configuration%
after_build:
 - ps: |
    $versionsuffix=$("{0:D4}" -f [convert]::ToInt32($env:APPVEYOR_BUILD_NUMBER, 10))
    if ($env:RUNTIME -ne "noruntime") {
       dotnet publish Rnwood.Smtp4dev -c $env:Configuration -f $env:FRAMEWORK -r $env:RUNTIME 	--version-suffix $versionsuffix
    } else {
       dotnet publish Rnwood.Smtp4dev -c $env:Configuration -f $env:FRAMEWORK --version-suffix $versionsuffix	
    }
artifacts:
- path: Rnwood.Smtp4dev\bin\$(configuration)\$(framework)\$(runtime)\publish
  name: Smtp4dev-$(runtime)-v$(appveyor_build_version)
  type: zip
- path: Rnwood.Smtp4dev\bin\$(configuration)\$(framework)\publish
  name: Smtp4dev-noruntime-v$(appveyor_build_version)
  type: zip
deploy:
  provider: GitHub
  artifact: /.*\..*/
  auth_token:
    secure: Zo0KGoJhNj/uyTTtab2G78ZM84NGgB6yznHfKPLBlwyN7bEuS11Vg7N+GtMd17tX
  prerelease: true
  on:
    branch: features
    appveyor_repo_tag: false
